### ISSUE TITLE
Progress Checklist

### ISSUE THREAD

**Issue by mektigboy** [mektigboy/SmartContractHacking#1]
# Progress Checklist

## Resources
- [x] Blockchain Theory 101 [Udemy]
- [ ] Learn Blockchain, Solidity and Full Stack Development with JavaScript [YouTube] (https://www.youtube.com/watch?v=gyMwXuJrbJQ)
- [x] What Ethereum Smart Contract Hacking Looks Like [YouTube] (https://www.youtube.com/watch?v=P8LXLoTUJ5g)
- [x] BHIS | Getting Started in Blockchain Security and Smart Contract Auditing | Beau Bullock [YouTube] (https://www.youtube.com/watch?v=WchXkMlKj9w)
- [x] How to find Solidity vulnerabilities [YouTube] (https://www.youtube.com/watch?v=R1eZCmR91vQ)
- [x] Secereum - Audit Techniques and Tools 101 (Ethereum Smart Contract Security) [YouTube] (https://www.youtube.com/watch?v=8IbkWnTLueU)
- [x] Auditing Smart Contracts - Security Review of Ethereum Applications [YouTube] (https://www.youtube.com/watch?v=LLiJK_VeAvQ)
- [x] Secereum - ETH 101 (Ethereum Smart Contract Security) [YouTube] (https://www.youtube.com/watch?v=admYLxNPROo)
- [x] An Overview of Blockchain-Based Smart Contract Security Vulnerabilities [YouTube] (https://www.youtube.com/watch?v=apCGPh7tKhw)
- [x] 10 Tips to become a Solidity EXPERT [YouTube] (https://www.youtube.com/watch?v=PeiTfWN7Ik0)
- [x]  Gas Optimization in Solidity: 10 tips [YouTube] (https://www.youtube.com/watch?v=PYilP2bjtwc)
- [x] The ideal smart contract audit report [YouTube] (https://www.youtube.com/watch?v=cpyQw5mwE_0)
- [x] Secereum - SOL 101 & 201 (Ethereum Smart Contract Security) [YouTube] (https://www.youtube.com/watch?v=65XiLy5Cxxk)
- [x] A Hacker’s Guide to Submitting Bugs on Immunefi [Medium] (https://medium.com/immunefi/a-hackers-guide-to-submitting-bugs-on-immunefi-1e6b7ada71a9)
- [x] Hacking Blockchain [YouTube] (https://www.youtube.com/watch?v=0gL6DsR6vGg) / Blockchain
- [x] Fuzzing Ethereum Smart Contract using Echidna - Blockchain Security #1 [YouTube] (https://www.youtube.com/watch?v=EA8_9x4D3Vk)
- [x] Ethereum Smart Contract Analysis & Solidity Audit using Mythril - Blockchain Security #2 [YouTube] (https://www.youtube.com/watch?v=fhOMTYkw8FM&list=PLa-iO6ehPFJgj7p7OKdMYsV0PBorLB7nY)
- [x] CryptoZombies [Website] (https://cryptozombies.io/)
- [x] Ethereum/EVM Smart Contract Reverse Engineering & Disassembly - Blockchain Security #3 [YouTube] (https://www.youtube.com/watch?v=I6VDBvX9Pkw)
- [x] Ethereum Smart Contract Analysis & Solidity Audit using Slither - Blockchain Security #4 [YouTube] (https://www.youtube.com/watch?v=s3FL5caAy5w)
- [x] DEVCON1: Understanding the Ethereum Blockchain Protocol - Vitalik Buterin [YouTube] (https://www.youtube.com/watch?v=gjwr-7PgpN8)
- [x] 7 Most Important Questions on Smart Contract Auditing [CH 1 | All About Smart Contract Audits] [YouTube] (https://www.youtube.com/watch?v=ms9xNtq9Y0w)
- [x] Access Control | Smart Contract Security Tutorial Part 1 [YouTube] (https://www.youtube.com/watch?v=Q1XlcAjHOBw)
- [x] Reentrancy Attack | Smart Contract Security Tutorial Part 2 [YouTube] (https://www.youtube.com/watch?v=3sIwIYfeOD8)
- [x] Reentrancy Attacks - A quick overview [YouTube] (https://www.youtube.com/watch?v=GoyLH2HUrCk)
- [x] Smart Contracts Risk Analysis and Flash Loan Exploits - Ethereum Security [YouTube] (https://www.youtube.com/watch?v=nLHCyEvszkc)

## Repo
- [ ] README.md
